version: "3.8"
services:
  server:
    build: ./
    ports:
      - ${SERVER_PORT}:8080
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    stdin_open: true
    tty: true
